In [156]:
import pandas as pd

In [157]:
transactions = pd.read_csv("db_transac (1).csv")

In [158]:
transactions.head()

,card_id,product_name,product_type,amt,is_xb,is_contactless,prch_date,prch_time,ctry_card,ctry_mrch,mrch,mcg_id
0,61349906,P2,Crédito,77.5,0,1,13/01/2024,00.11.34,El Salvador,Ecuador,"Meyer, Flores and Mason",8
1,10197801,P2,Credito,268.8,1,0,21/01/2024,21:49:56,Argentina,Ecuador,Robbins and Sons,7
2,82320887,P2,Credit,51.2,0,1,04/01/2024,15.06.03,Chile,Argentina,Garcia LLC,1
3,60630825,P2,Credit,3.5,0,1,10-01-2024,04:11:00,Brasil,Brazil,Campos Ltd,2
4,74940553,P2,Debit,29.5,0,1,01/01/2024,08:03:42,Mexico,Brazil,Thomas-Dickson,6

In [159]:
transactions['is_xb'].value_counts()

is_xb
0    1462017
1     937983
Name: count, dtype: int64

In [160]:
transactions['is_contactless'].value_counts()

is_contactless
1    1352622
0    1047378
Name: count, dtype: int64

In [161]:
transactions.dtypes

card_id             int64
product_name       object
product_type       object
amt               float64
is_xb               int64
is_contactless      int64
prch_date          object
prch_time          object
ctry_card          object
ctry_mrch          object
mrch               object
mcg_id              int64
dtype: object

In [162]:
transactions['prch_date'] = transactions['prch_date'].str.replace('/', '-', regex=False)

transactions['prch_date'].head(20)

0     13-01-2024
1     21-01-2024
2     04-01-2024
3     10-01-2024
4     01-01-2024
5     17-01-2024
6     18-01-2024
7     22-01-2024
8     23-01-2024
9     11-01-2024
10    15-01-2024
11    23-01-2024
12    16-01-2024
13    13-01-2024
14    03-01-2024
15    23-01-2024
16    06-01-2024
17    24-01-2024
18    28-01-2024
19    26-01-2024
Name: prch_date, dtype: object

In [163]:
transactions['prch_time'].head(20)

transactions['prch_time'] = transactions['prch_time'].str.replace('.', ':', regex=False)

transactions['prch_time'].head(20)

0     00:11:34
1     21:49:56
2     15:06:03
3     04:11:00
4     08:03:42
5     18:51:29
6     04:08:28
7     07:33:53
8     23:58:27
9     04:28:13
10    00:30:30
11    04:56:44
12    23:37:41
13    05:31:56
14    04:33:26
15    00:08:22
16    17:58:21
17    21:13:00
18    15:39:48
19    07:16:57
Name: prch_time, dtype: object

In [164]:
transactions['product_type'].value_counts()

product_type
Credit     1022912
Credito     654147
Crédito     363900
Debit       193380
Debito      117039
Débito       48622
Name: count, dtype: int64

In [165]:
transactions['product_type'] = transactions['product_type'].replace(
    {'Debit': 'Debito', 'Debito': 'Debito', 'Débito': 'Debito',
     'Crédito': 'Credito', 'Credito': 'Credito', 'Credit': 'Credito'}
)

transactions['product_type'].value_counts()

product_type
Credito    2040959
Debito      359041
Name: count, dtype: int64

In [166]:
transactions['prch_date'] = pd.to_datetime(transactions['prch_date'], errors='coerce')

transactions['prch_datetime'] = transactions['prch_date'] + pd.to_timedelta(transactions['prch_time'], errors='coerce')

transactions[['prch_date', 'prch_time', 'prch_datetime']].head()

/var/folders/0z/4yrpt4m15ps8kzs2ljkgk40r0000gn/T/ipykernel_20276/3158875960.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  transactions['prch_date'] = pd.to_datetime(transactions['prch_date'], errors='coerce')

   prch_date prch_time       prch_datetime
0 2024-01-13  00:11:34 2024-01-13 00:11:34
1 2024-01-21  21:49:56 2024-01-21 21:49:56
2 2024-01-04  15:06:03 2024-01-04 15:06:03
3 2024-01-10  04:11:00 2024-01-10 04:11:00
4 2024-01-01  08:03:42 2024-01-01 08:03:42

In [167]:
#years in datetime
transactions['year'] = transactions['prch_datetime'].dt.year
transactions['year'].value_counts()

year
2024    2400000
Name: count, dtype: int64

In [168]:
transactions['trimester_year'] = transactions['prch_datetime'].dt.to_period('Q').astype(str)

transactions['trimester_year'].value_counts()

trimester_year
2024Q2    1350000
2024Q1    1050000
Name: count, dtype: int64

In [169]:
#percentiles of amount
transactions['amt'].describe(percentiles=[0.25, 0.5, 0.75, 0.9, 0.95, 0.99])

count    2.400000e+06
mean     1.792186e+02
std      3.251429e+02
min     -5.126200e+03
25%      3.480000e+01
50%      7.930000e+01
75%      1.783000e+02
90%      4.014000e+02
95%      7.019000e+02
99%      1.675301e+03
max      1.109100e+04
Name: amt, dtype: float64

In [170]:
transactions['ctry_card'] = transactions['ctry_card'].replace({'Brazil': 'Brasil', 'Perú': 'Peru', 'Mexico': 'México', 'Panamá':'Panama', 'República Dominicana': 'Republica Dominicana'})

transactions['ctry_card'].value_counts()

ctry_card
Brasil                  476516
México                  476398
Argentina               358609
Colombia                238211
Chile                   194259
Peru                    168548
Ecuador                 124301
Panama                  117495
Guatemala                47615
Republica Dominicana     38139
Bolivia                  37336
El Salvador              26145
Uruguay                  24814
Costa Rica               24453
Honduras                 22319
Nicaragua                12692
Paraguay                 12150
Name: count, dtype: int64

In [171]:
transactions['ctry_mrch'] = transactions['ctry_mrch'].replace({'Brazil': 'Brasil', 'Perú': 'Peru', 'Mexico': 'México', 'Panamá':'Panama', 'República Dominicana': 'Republica Dominicana'})

transactions['ctry_mrch'].value_counts()

ctry_mrch
México                  479907
Brasil                  479813
Argentina               359999
Colombia                240693
Chile                   191853
Peru                    167640
Ecuador                 120136
Panama                  120041
Guatemala                47924
Republica Dominicana     36383
Bolivia                  36046
Uruguay                  24248
Honduras                 24026
Costa Rica               23790
El Salvador              23717
Paraguay                 11939
Nicaragua                11845
Name: count, dtype: int64

In [172]:
#save transactions to csv
transactions.to_csv("transactions_cleaned.csv", index=False)